[platformio]
default_envs = uno_logic
src_dir = uno_firmware/crop_chop_uno_logic

[env:uno_logic]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
upload_speed = 115200
upload_flags =
  -V
