[platformio]
default_envs = xiao_esp32s3_sense

[env:xiao_esp32s3_sense]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
upload_speed = 460800
build_flags =
  -DARDUINO_XIAO_ESP32S3
  -DCAMERA_MODEL_XIAO_ESP32S3
  -DBOARD_HAS_PSRAM
  -DCORE_DEBUG_LEVEL=1
board_build.partitions = default_8MB.csv
board_build.flash_mode = qio
board_build.arduino.memory_type = qio_opi
